#
# Module manifest for module 'OperationValidation'
#
# Generated by: jimtru
#
# Generated on: 3/18/2015
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'OperationValidation.psm1'
# ModuleToProcess = 'OperationValidation.psm1'

# Version number of this module.
ModuleVersion = '1.3.0'

# ID used to uniquely identify this module
GUID = '25bd9e34-bff9-4552-a23d-854857b42462'

# Author of this module
Author = 'jimtru'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) 2015 jimtru. All rights reserved.'

# Description of the functionality provided by this module
Description = 'A set of tools for executing validation of the operation of a system. It provides a way to organize and execute Pester tests which are written to validate operation (rather than limited feature tests)'

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @('Pester')

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @('OperationValidation.Format.ps1xml')

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = @(
    'Get-OperationValidation'
    'Invoke-OperationValidation'
)

# Cmdlets to export from this module
# CmdletsToExport = '*'

# Variables to export from this module
# VariablesToExport = '*'

# Aliases to export from this module
# AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @(
    'OperationValidation.Format.ps1xml'
    'OperationValidation.psd1'
    'OperationValidation.psm1'
    'Diagnostics\Comprehensive\PSGallery.Comprehensive.Tests.ps1'
    'Diagnostics\Simple\PSGallery.Simple.Tests.ps1'
    'Private\Convert-TestResult.ps1'
    'Private\Get-ModuleList.ps1'
    'Private\Get-TestCaseNamesFromAst.ps1'
    'Private\Get-TestFromAst.ps1'
    'Private\Get-TestFromScript.ps1'
    'Private\Get-TestName.ps1'
    'Private\New-OperationValidationFailure.ps1'
    'Private\New-OperationValidationInfo.ps1'
    'Private\New-OperationValidationInfo.ps1'
    'Private\New-OperationValidationResult.ps1'
    'Private\Parse-Psd1.ps1'
    'Public\Get-OperationValidation.ps1'
    'Public\Invoke-OperationValidation.ps1'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Operation', 'Validation', 'Infrastructure', 'Testing', 'Pester', 'OVF', 'PSEdition_Desktop', 'PSEdition_Core')

        # A URL to the license for this module.
        LicenseUri = 'https://raw.githubusercontent.com/PowerShell/Operation-Validation-Framework/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/PowerShell/Operation-Validation-Framework'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'https://raw.githubusercontent.com/PowerShell/Operation-Validation-Framework/master/CHANGELOG.md'

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

